server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall_product?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
